source 'https://github.com/CocoaPods/Specs.git'

platform:ios,’9.0’
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

def pods
    #Swift
    pod 'Alamofire', '~> 4.7.3'
    pod 'Cache'
    pod 'HandyJSON', '~> 4.2.0'
end

target 'app' do
    pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
